repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.5.5
    hooks:
    - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    - id: mypy
      additional_dependencies:
      - litestar
      - pydantic
      - pydantic-settings
      - types-dateparser
      - types-python-dateutil
      - pint
      - stamina
      - types-PyYAML
